class App < Sinatra::Base

  # user list
  get '/user/list' do
    @users = User.all
    haml :'user/list'
  end

  # add a user
  get '/user/add' do
    haml :'user/add'
  end

  post '/user/add' do
    nice_params = escape_html_for_set(params)
    user = User.create({name: nice_params['name'], first_name: nice_params['first_name'], email: nice_params['email'], image: nice_params['image']})
    flash[:notice] = 'User created successfully'
    redirect "/user/profile/#{user.id}"
  end

  # profile page
  get '/user/profile/:id' do
    @this_user = User.find(params[:id])
    haml :'user/profile'
  end

  # self sign-up
  post '/signup' do
    # generate a token and email it
    token = SecureRandom.urlsafe_base64
    address = params['email']
    $redis.set(token,address)
    message = Mail.new do
      from            ENV['MAIL_FROM']
      to              address
      subject         'IWTA Handicap Signup'
      content_type    'text/html; charset=UTF-8'
      body            "<p>Thanks for signing up. To continue, please click the link:-</p><p><a href='http://iwta.marsupialmusic.net/signup/#{token}'>Continue to sign up</a></p><p>--</p><p>Generated by IWTA Handicapping System. If you did not initiate this email, please delete and/or contact sja@marsupialmusic.net</p>"
      delivery_method Mail::Postmark, api_token: ENV['POSTMARK_API_TOKEN']
    end
    message.deliver
    flash[:notice] = 'Please check your email for next steps'
    redirect '/'
  end

  # link handling for self sign-up
  get '/signup/:token' do
    @email = $redis.get(params['token'])
    haml :'user/signup'
  end

  # form handling for final step sign-up
  post '/signup/complete' do
    puts params.inspect
    @user = User.create(
      name:                   params['name'],
      email:                  params['email'],
      first_name:             params['first_name'],
      last_name:              params['last_name'],
      password:               params['password'],
      password_confirmation:  params['password2']
    )
    session['email'] = @user.email
    redirect '/'
  end


end
