require_relative 'user'
require_relative 'competition'
require_relative 'season'
require_relative 'game'
require_relative 'course'
require_relative 'round'
require_relative 'tee'
require_relative 'batch'
